name: Deploy Portfolio WebApp to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/main.yml
      - README.md
      - LICENSE
      - .gitignore
 
  pull_request:
      branches:
        - main
  workflow_dispatch:
    
    
 
jobs:
  deploy:
    environment: Production
    if: github.ref == 'refs/heads/main'
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl daemon-reload
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            # Remove existing contents of /var/www/html
            sudo rm -rf /var/www/html/*
            # Move new files to /var/www/html
            sudo mv * /var/www/html
            # Set permissions for the web server
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            # Restart Apache to apply changes
            sudo systemctl restart apache2
            echo "Deployment completed successfully!"

      