name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      workflow_name:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: 'deployments'
          SLACK_COLOR: ${{ inputs.status == 'success' && 'good' || 'danger' }}
          SLACK_MESSAGE: |
            ${{ inputs.workflow_name }} - ${{ inputs.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}