name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      workflow_name:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        run: |
          COLOR="${{ inputs.status == 'success' && 'good' || 'danger' }}"
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [{
                \"color\": \"$COLOR\",
                \"title\": \"${{ inputs.workflow_name }}\",
                \"text\": \"Status: ${{ inputs.status }}\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nAuthor: ${{ github.actor }}\"
              }]
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}